### ISSUE TITLE
如何管理 nixos-cn.org 的 DNS？

### ISSUE THREAD

**Issue by CyrusYip** [nixos-cn/nixos-cn-org-configurations#1]
相关资料：

- [Accounts, zones, and profiles · Cloudflare Fundamentals docs](https://developers.cloudflare.com/fundamentals/get-started/concepts/accounts-and-zones/)
- [Terraform Registry](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs)

Cloudflare 这边使用 Edit zone DNS 模板创建 API Token 就可以了。

**Comment by linyinfeng** [comment]
我们可以效仿 NixOS 官方管理 nixos.org 域名及其服务器的做法。

[NixOS/nixos-org-configurations](https://github.com/NixOS/nixos-org-configurations) 仓库通过这些做法妥善管理 NixOS 官方组织的所有基础设施：
1. 通过 [docs/inventory.md](https://github.com/NixOS/nixos-org-configurations/blob/master/docs/inventory.md) 详细记录所有基础设施资产的所有者，和各种重要信息，比如 DNS 提供商。
2. 通过 [terraform](https://github.com/NixOS/nixos-org-configurations/tree/master/terraform) 管理 DNS 等 nixos 无法管理的基础设施。
3. 服务器配置使用 nixos 管理，这部分展开会很复杂，比如如何更新，如何管理 secrets 等，但暂时不用做任何设计，因为我们现在一台服务器也没有。

由于我们只有一个域名，因此我们只需要做到 1 和 2 即可。其中 2 的细节需要进一步讨论。主要问题在于如何安全地存储 terraform state，是用 terraform cloud，还是加密存进仓库，还是使用其他方式。

**Comment by linyinfeng** [comment]
由于本仓库的主题是（将来会有的） nixos-cn.org 主页。我建立了 [nixos-cn/nixos-cn-org-configurations](https://github.com/nixos-cn/nixos-cn-org-configurations)，并转移该 issue 到新仓库继续讨论。

**Comment by CyrusYip** [comment]
可以先整个 docs/inventory.md，terraform 我正在了解。

**Comment by linyinfeng** [comment]
> 可以先整个 docs/inventory.md，terraform 我正在了解。

那我立刻编写一个，请问现在 nixos-cn.org 的域名注册商是？DNS 是托管在 cloudflare 对吧。

**Comment by CyrusYip** [comment]
目前注册商是 https://porkbun.com ，DNS  托管在 cloudflare。

**Comment by linyinfeng** [comment]
https://github.com/nixos-cn/nixos-cn-org-configurations/commit/74da1956ae51a87bfd76dd8f90a1b05acd017c17 写好了基本的 resource inventory.

**Comment by linyinfeng** [comment]
> 可以先整个 docs/inventory.md，terraform 我正在了解。

我看了下 terraform 的免费计划的内容。我认为我们可以先使用 terraform cloud，因为如果加密 terraform state，私钥由谁持有还是会成为一个问题，而且迁移并不困难，terraform state 可以随时从 cloud 上导出。

Terraform Cloud 的免费计划是，每个组织最多五个用户，由于我们的基础设施和维护基础设施的人很少，五个用户应该是足够的。

**Comment by linyinfeng** [comment]
> 可以先整个 docs/inventory.md，terraform 我正在了解。

我建立一个 terraform cloud 组织并邀请你吧，请联系我告知你的邮箱，我正在编写初始的 terraform 配置。

**Comment by CyrusYip** [comment]
给你发邮件了。

**Comment by CyrusYip** [comment]
@linyinfeng 我已经进组织了。下一步是？

**Comment by CyrusYip** [comment]
@linyinfeng  我刚看了文档 https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs ，第一次接触，搞不懂。你比较懂这些，要不我在 porkbun 那边把 authoritative nameservers 改成你的，这样你就可以管理 DNS 了。

**Comment by CyrusYip** [comment]
https://github.com/nixos-cn/nixos-cn-org-configurations/pull/3

目前使用 terraform 管理。
